### ISSUE TITLE
D1-17 - błędna odpowiedź

### ISSUE THREAD

**Issue by mamut-tme** [rafal-dot/UKE-nowe-pytania#1]
W pytaniu D1-17: 
Jaka jest zależność fazowa między przepływającym prądem a napięciem w szeregowym obwodzie rezonansowym w rezonansie?

moim zdaniem prawidłowa jest odpowiedź C:
c. napięcie i prąd są zgodne w fazie

Wynika to z tego, że podczas rezonansu Z=R, a w układach o charakterze całkowicie rezystancyjnych faza napięcia i prądu jest taka sama. 
![image](https://github.com/rafal-dot/UKE-nowe-pytania/assets/54120608/54f478c7-bfc6-45e5-98ab-60d4ea192e3f)
źródło Elektrotechnika, Stanisław Bolkowski, WSiP 1993
na charakterystyce φ(fr)=0

**Comment by rafal-dot** [comment]
Poprawione
