### ISSUE TITLE
Odpowiedź do pytania d1-10

### ISSUE THREAD

**Issue by SenatorBeaver** [rafal-dot/UKE-nowe-pytania#3]
Brak odpowiedzi w arkuszu.

We wzmacniaczu tranzystorowym w układzie wspólnego kolektora obciążenie jest dołączane między:
Prawidłowa odpowiedź to c - emiter a masę

źródło:
https://pl.wikipedia.org/wiki/Wsp%C3%B3lny_kolektor

**Comment by rafal-dot** [comment]
Fixed
