### ISSUE TITLE
Odpowiedź do d1-15

### ISSUE THREAD

**Issue by SenatorBeaver** [rafal-dot/UKE-nowe-pytania#4]
Prawidłowa odpowiedź to a (w rezonansie stanowią tylko rezystancję)

Źródło: https://pl.wikibooks.org/wiki/Wprowadzenie_do_elektroniki/Obwody_R,L,C
"W rezonansie obwód ma najmniejszą impedancję równą R."

Wzór na impedancję to 
Z = sqrt(R^2 + (XL - XC)^2))
Warunek rezonansu to reaktancja pojemnościowa i reaktancja indukcyjna są równe

**Comment by rafal-dot** [comment]
Fixed
